### ISSUE TITLE
Mejorar la vista de información de los candidatos

### ISSUE THREAD

**Issue by alvarovp27** [EGC1617Grupo/agora-gui-elections#19]
En la vista principal de una elección, donde se muestra la información de los candidatos, tan solo se muestra el nombre de los mismos. Podría ser mejorado si se mostrara toda la información extra que tiene un candidato.
- url: https://agora/election/{id}/public/home
- imagen para orientar el problema:
![image](https://cloud.githubusercontent.com/assets/10280862/21203084/339cfc6e-c251-11e6-9863-c0f62c88d159.png)

**Comment by alvarovp27** [comment]
Se ha solucionado en una serie de commits en la rama feature/ui-improvement. El último de los commits es el siguiente: 2ad74d6715c195fcc69d30c75bc0a2de434f8870.

Los siguientes ficheros han sido modificados:
- simple-question-directive.html
Modificada la parte en la que se muestran los candidatos. Se ha añadido el siguiente código:
```HTML
  <div ng-repeat="answer in question.answers">
    <div class="answer-header">
      <h4>{{answer.text}}</h4>
      <a ng-show="{{answer.urls || answer.category || answer.details}}" href="javascript:;"><span class="glyphicon glyphicon-chevron-down" ng-click="hiddenAnswer = !hiddenAnswer"/></a>
    </div>
    <div ng-show="{{answer.urls || answer.category || answer.details}}">
      <div class="answer-info" ng-show="hiddenAnswer">
        <p ng-show="answer.urls[1].url"><img class="img-responsive img-rounded answer-img" ng-src="{{answer.urls[1].url}}"></img></p>
        <p ng-show="answer.category"><span ng-i18next="[html:i18next]({method: tallyMethod})avElection.public.category"></span> {{answer.category}}</p>
        <p ng-show="answer.urls[0].url"><span ng-i18next="[html:i18next]({method: tallyMethod})avElection.public.webPage"></span> <a ng-href="{{answer.urls[0].url}}">{{answer.urls[0].url}}</a></p>
        <p ng-show="answer.details"><span ng-i18next="[html:i18next]({method: tallyMethod})avElection.public.category"></span></p>
        <p><pre ng-show="answer.details">{{answer.details}}</pre></p>
      </div>
    </div>
  </div>
```
Este código muestra toda la información de un candidato: categoría, página web, imagen del mismo, y detalles. Los nombres de los cambios están internacionalizados. Se han modificado los siguientes ficheros json de internacionalización:
- en.json
- es.json
- ca.json
- gl.json
También, se ha añadido un botón al lado del nombre del candidato. Cuando se pulsa, se despliegan sus detalles. Solo se mostrará la información del candidato si existe dicha información. Si únicamente tiene definido el nombre, no se mostrará.

- simple-question-directive.less
Se ha añadido el siguiente código:
```CSS
 .answer-img{
    max-width: 200px;
    max-height: 200px;
    margin-top: 20px;
    margin-bottom: 20px;
  }
```
La clase .answer-img, ajusta el tamaño de la imagen para que no supere los 200px, tanto en ancho como en largo. Además, se ha añadido un margen tanto arriba como abajo de la misma.
```CSS
  .answer-info{
    @media (min-width:768px){
      margin-left: 50px; 
      margin-bottom: 50px; 
    }

    @media (max-width: 767px){
      margin-bottom: 50px;
    }
  }
```
Esta clase es usada para mostrar el bloque de información del candidato. Si el dispositivo es mayor de 768px, añade un margen a la izquierda y abajo. De lo contrario, únicamente añadirá un margen por abajo.
```CSS
  .answer-header > h3, .answer-header > h4 {
    display: inline-block;
  }
```
Esta sección CSS, nos servirá para situar en la misma línea los header y los iconos para expandir la información.
```CSS
  .answer-header span {
    margin-left:10px;
  }
```
Separa 10px el icono para expandir la información del candidato.
```CSS
  body {
    word-wrap: break-word;
  }
```
Hace, que para todo el cuerpo del HTML en esta página, si una palabra no cabe, se parta. Así evitamos
que, en dispositivos pequeños, no quepa la información en pantalla.

Adjunto una imagen con la solución al problema.
![image](https://cloud.githubusercontent.com/assets/10280862/21203131/634f25b8-c251-11e6-8c14-ba71208ddd4f.png)
